### ISSUE TITLE
is data still available?

### ISSUE THREAD

**Issue by penolove** [klarna/product-page-dataset#21]
https://github.com/klarna/product-page-dataset#download-under-the-creative-commons-by-nc-sa-license

it shows Access Denied while I download it
![image](https://user-images.githubusercontent.com/9348557/236108297-b3b59465-6c17-4f75-9f63-d7739ee94d1b.png)

**Comment by alexandrahotti** [comment]
Hi,
Thank you for bringing this to our attention. It is still our intention that the dataset should be publicly available, and we are investigating the issue.

**Comment by alexandrahotti** [comment]
Hi, 
We are currently updating our dataset hosting platform, and the dataset will be made public again early this fall. Sorry for the inconvenience.

**Comment by alexandrahotti** [comment]
Hi,
The maintenance is now finished, and you can now download the Klarna Product Page Dataset through the links.
